spring:
  application:
    name: reservation-service
  mvc:
    throw-exception-if-no-handler-found: true
    converters:
      preferred-json-mapper: gson
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_db
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

  gson:
    date-format: yyyy-MM-dd HH:mm:ss
    enable-complex-map-key-serialization: true
    serialize-nulls: true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos              # ← 改成你的
        password: nacos              # ← 改成你的
        namespace: tushuguan         # ← 你截图里的 namespaceId
        naming-load-cache-at-start: true
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

server:
  port: 8083

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.security: DEBUG

